name: Build and deploy Node.js app to Azure Web App - bellisima
on:
 push:
   branches: 
     - master
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
   
   steps:
   - uses: actions/checkout@v4
   
   - name: Set up Node.js version
     uses: actions/setup-node@v3
     with:
       node-version: '18.x'
   
   - name: Show GitHub Actions Runner IP
     run: |
       ip=$(curl -s https://api.ipify.org)
       echo "GitHub Actions Runner IP is: $ip"
   
   - name: Create .env file
     working-directory: backend
     run: |
       touch .env
       echo "PORT=3000" >> .env
       echo "NODE_ENV=production" >> .env
       echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
       echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
       echo "JWT_EXPIRES_IN=7d" >> .env
       echo "CULQI_PUBLIC_KEY=${{ secrets.CULQI_PUBLIC_KEY }}" >> .env
       echo "CULQI_PRIVATE_KEY=${{ secrets.CULQI_PRIVATE_KEY }}" >> .env
       echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
       echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
   
   - name: npm install and build
     working-directory: backend
     run: |
       npm install
       npm run build
     
   - name: Run tests
     working-directory: backend
     run: |
       npm test
   
   - name: Zip artifact for deployment
     working-directory: backend
     run: zip -r ../release.zip .
   
   - name: Upload artifact for deployment job
     uses: actions/upload-artifact@v4
     with:
       name: node-app
       path: release.zip
 
 deploy:
   runs-on: ubuntu-latest
   needs: build
   environment:
     name: 'Production'
     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
   
   permissions:
     id-token: write
     contents: read
   
   steps:
   - name: Download artifact from build job
     uses: actions/download-artifact@v4
     with:
       name: node-app
   
   - name: Unzip artifact for deployment
     run: unzip release.zip
   
   - name: Login to Azure
     uses: azure/login@v2
     with:
       client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9EE7EAFE80A4400498B55B4AA513E04B }}
       tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A647789121D346E98A63218075ECD192 }}
       subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E1CD65E8443A404CA9D25CA36D5CBD4F }}
   
   - name: 'Deploy to Azure Web App'
     id: deploy-to-webapp
     uses: azure/webapps-deploy@v3
     with:
       app-name: 'bellisima'
       slot-name: 'Production'
       package: release.zip
